### ISSUE TITLE
no pb version for mapply/mcmapply?

### ISSUE THREAD

**Issue by japhir** [psolymos/pbapply#29] opened 2017-09-26 15:19 UTC
Hi! Am I understanding correctly that there is no pb version of mapply? I'm running a complicated function on a long dataframe of different parameter configurations. Since it is taking so long, I thought it might be nice to show a progress bar. A version that also works with mcmapply (the parallel version of mapply) would be even better.

Cheers!

**Comment by psolymos** [comment] 2017-09-26 16:10
@japhir : I have looked at it in the past, but the problem is that `mapply` uses `.Internal(mapply(FUN, dots, MoreArgs))` which is not as straightforward to hack. R ext doc says:

> It is not portable to call compiled code in R or other packages via `.Internal`, `.C`,
> `.Fortran`, `.Call` or `.External`, since such interfaces are subject to change without
> notice and will probably result in your code terminating the R process.

I will give it a thought, but suggestions are welcome!

**Comment by japhir** [comment] 2017-09-26 16:25
Sounds like you've looked into it already. The parallel computing functions I'm using now are all new to me, so I don't think I can be of help in this instance :(. Thanks!

**Comment by zzawadz** [comment] 2018-01-17 18:58
Maybe a code like this can be used here:

```
pbmapply <- function(FUN, ..., MoreArgs = NULL) {
  args <- list(...)
  result <- list()
  
  for(i in seq_along(args[[1]])) {
    argList <- list()
    for(j in 1:length(args)) {
      argList[[j]] <- args[[j]][[i]]
    }
    result[[i]] <- do.call(FUN, c(argList, MoreArgs))
  }
  result
}

a <- pbmapply(function(x, y) x * y, 1:10, 1:10)
```

However, I think that creating of the `argList` will be an overkill:(

All other stuff like recycling over the longest vector in the arguments are only an implementations details.

**Comment by zzawadz** [comment] 2018-09-04 19:08
Maybe something like this? I add a `trace` expression to the called function. Then I pass it to the standard mapply. What do you think @psolymos?

I don't know if it's production ready but I'll prepare a pull request with a bunch of tests. I'm worried about the
`env <- parent.frame(6)`, because I don't trust counting the number of parent envs...

```
pbmapply <- function(FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE) {
  
  pb <- pbapply::startpb()
  on.exit(closepb(pb))
  NN <- max(sapply(list(...), length))
  STEP <- 1 / NN
  VALUE <- 0
  
  env <- new.env()
  env$FUN <- FUN
      
  suppressMessages(trace(quote(FUN), exit = quote({
    env <- parent.frame(6)
    env$VALUE <- env$VALUE + env$STEP
    pbapply::setpb(parent.frame(6)$pb, env$VALUE)
  }), where = env, print = FALSE))
  
  
  mapply(env$FUN, ..., MoreArgs = MoreArgs, SIMPLIFY = SIMPLIFY, USE.NAMES = USE.NAMES)
  
}

pbmapply(function(x, y) {
  Sys.sleep(1)
  x + y
}, 1:10, 1:10)

```

**Comment by psolymos** [comment] 2018-09-07 16:12
PR #36 closed this issue

**Closed by psolymos** 2018-09-07 16:12 UTC
Labels: new-feature

**Comment by sdanielzafar** [comment] 2019-02-05 16:51
When will this go to CRAN?

**Comment by noahhaber** [comment] 2019-02-05 17:58
I was just thinking that! Would be really great to make this more publicly accessible.

**Comment by psolymos** [comment] 2019-02-05 20:49
On it ... it somehow slipped my mind 😄 . Thanks for nudging me!

**Comment by psolymos** [comment] 2019-02-05 21:47
Submitted 1.4-0 to CRAN
